-- simAssimp lua type-checking wrapper
-- (this file is automatically generated: do not edit)
require 'checkargs'

local simAssimp=require('simAssimp')

function simAssimp.__addTypeCheck()
    local function wrapFunc(funcName,wrapperGenerator)
        _G['simAssimp'][funcName]=wrapperGenerator(_G['simAssimp'][funcName])
    end

    wrapFunc('importShapesDlg',function(origFunc)
        return function(...)
            filename=checkargsEx(
                {level=1},
                {
                    {type='string'},
                },
                ...
            )
            return origFunc(filename)
        end
    end)

    wrapFunc('exportShapesDlg',function(origFunc)
        return function(...)
            filename,shapeHandles=checkargsEx(
                {level=1},
                {
                    {type='string'},
                    {type='table',item_type='int'},
                },
                ...
            )
            return origFunc(filename,shapeHandles)
        end
    end)

end

sim.registerScriptFuncHook('sysCall_init','simAssimp.__addTypeCheck',true)

return simAssimp
