-- simB0 lua type-checking wrapper
-- (this file is automatically generated: do not edit)
require 'checkargs'

local simB0=require('simB0')

function simB0.__addTypeCheck()
    local function wrapFunc(funcName,wrapperGenerator)
        _G['simB0'][funcName]=wrapperGenerator(_G['simB0'][funcName])
    end

    wrapFunc('nodeSpin',function(origFunc)
        return function(...)
            handle=checkargsEx(
                {level=1},
                {
                    {type='string'},
                },
                ...
            )
            return origFunc(handle)
        end
    end)

    wrapFunc('pingResolver',function(origFunc)
        return function(...)
            checkargsEx(
                {level=1},
                {
                },
                ...
            )
            return origFunc()
        end
    end)

    wrapFunc('serviceClientCallJSON',function(origFunc)
        return function(...)
            serviceClientHandle,request=checkargsEx(
                {level=1},
                {
                    {type='string'},
                    {type='table'},
                },
                ...
            )
            return origFunc(serviceClientHandle,request)
        end
    end)

end

sim.registerScriptFuncHook('sysCall_init','simB0.__addTypeCheck',true)

return simB0
