-- simCodeEditor lua type-checking wrapper
-- (this file is automatically generated: do not edit)
require 'checkargs'

local simCodeEditor=require('simCodeEditor')

function simCodeEditor.__addTypeCheck()
    local function wrapFunc(funcName,wrapperGenerator)
        _G['simCodeEditor'][funcName]=wrapperGenerator(_G['simCodeEditor'][funcName])
    end

end

sim.registerScriptFuncHook('sysCall_init','simCodeEditor.__addTypeCheck',true)

return simCodeEditor
