-- simEigen lua type-checking wrapper
-- (this file is automatically generated: do not edit)
require 'checkargs'

local simEigen=require('simEigen')

function simEigen.__addTypeCheck()
    local function wrapFunc(funcName,wrapperGenerator)
        _G['simEigen'][funcName]=wrapperGenerator(_G['simEigen'][funcName])
    end

end

sim.registerScriptFuncHook('sysCall_init','simEigen.__addTypeCheck',true)

return simEigen
