-- simIM lua type-checking wrapper
-- (this file is automatically generated: do not edit)
require 'checkargs'

local simIM=require('simIM')

function simIM.__addTypeCheck()
    local function wrapFunc(funcName,wrapperGenerator)
        _G['simIM'][funcName]=wrapperGenerator(_G['simIM'][funcName])
    end

    wrapFunc('dataURL',function(origFunc)
        return function(...)
            imgHandle,format=checkargsEx(
                {level=1},
                {
                    {type='string'},
                    {type='string',default='BMP'},
                },
                ...
            )
            return origFunc(imgHandle,format)
        end
    end)

end

sim.registerScriptFuncHook('sysCall_init','simIM.__addTypeCheck',true)

return simIM
