-- simLuaCmd lua type-checking wrapper
-- (this file is automatically generated: do not edit)
require 'checkargs'

local simLuaCmd=require('simLuaCmd')

function simLuaCmd.__addTypeCheck()
    local function wrapFunc(funcName,wrapperGenerator)
        _G['simLuaCmd'][funcName]=wrapperGenerator(_G['simLuaCmd'][funcName])
    end

end

sim.registerScriptFuncHook('sysCall_init','simLuaCmd.__addTypeCheck',true)

return simLuaCmd
