-- simQML lua type-checking wrapper
-- (this file is automatically generated: do not edit)
require 'checkargs'

local simQML=require('simQML')

function simQML.__addTypeCheck()
    local function wrapFunc(funcName,wrapperGenerator)
        _G['simQML'][funcName]=wrapperGenerator(_G['simQML'][funcName])
    end

    wrapFunc('sendEvent',function(origFunc)
        return function(...)
            engine,name,data=checkargsEx(
                {level=1},
                {
                    {type='string'},
                    {type='string'},
                    {type='table'},
                },
                ...
            )
            return origFunc(engine,name,data)
        end
    end)

    wrapFunc('setEventHandler',function(origFunc)
        return function(...)
            engine,funcName=checkargsEx(
                {level=1},
                {
                    {type='string'},
                    {type='string'},
                },
                ...
            )
            return origFunc(engine,funcName)
        end
    end)

end

sim.registerScriptFuncHook('sysCall_init','simQML.__addTypeCheck',true)

return simQML
