-- simSDF lua type-checking wrapper
-- (this file is automatically generated: do not edit)
require 'checkargs'

local simSDF=require('simSDF')

function simSDF.__addTypeCheck()
    local function wrapFunc(funcName,wrapperGenerator)
        _G['simSDF'][funcName]=wrapperGenerator(_G['simSDF'][funcName])
    end

end

sim.registerScriptFuncHook('sysCall_init','simSDF.__addTypeCheck',true)

return simSDF
