-- simUI lua type-checking wrapper
-- (this file is automatically generated: do not edit)
require 'checkargs'

local simUI=require('simUI')

function simUI.__addTypeCheck()
    local function wrapFunc(funcName,wrapperGenerator)
        _G['simUI'][funcName]=wrapperGenerator(_G['simUI'][funcName])
    end

    wrapFunc('insertTableRow',function(origFunc)
        return function(...)
            ui,widget,index=checkargsEx(
                {level=1},
                {
                    {type='int'},
                    {type='int'},
                    {type='int'},
                },
                ...
            )
            return origFunc(ui,widget,index)
        end
    end)

    wrapFunc('removeTableRow',function(origFunc)
        return function(...)
            ui,widget,index=checkargsEx(
                {level=1},
                {
                    {type='int'},
                    {type='int'},
                    {type='int'},
                },
                ...
            )
            return origFunc(ui,widget,index)
        end
    end)

    wrapFunc('insertTableColumn',function(origFunc)
        return function(...)
            ui,widget,index=checkargsEx(
                {level=1},
                {
                    {type='int'},
                    {type='int'},
                    {type='int'},
                },
                ...
            )
            return origFunc(ui,widget,index)
        end
    end)

    wrapFunc('removeTableColumn',function(origFunc)
        return function(...)
            ui,widget,index=checkargsEx(
                {level=1},
                {
                    {type='int'},
                    {type='int'},
                    {type='int'},
                },
                ...
            )
            return origFunc(ui,widget,index)
        end
    end)

    wrapFunc('setScene3DNodeParam',function(origFunc)
        return function(...)
            ui,widget,nodeId,paramName,paramValue=checkargsEx(
                {level=1},
                {
                    {type='int'},
                    {type='int'},
                    {type='int'},
                    {type='string'},
                    {type='any'},
                },
                ...
            )
            return origFunc(ui,widget,nodeId,paramName,paramValue)
        end
    end)

end

sim.registerScriptFuncHook('sysCall_init','simUI.__addTypeCheck',true)

return simUI
