-- simURLDrop lua type-checking wrapper
-- (this file is automatically generated: do not edit)
require 'checkargs'

local simURLDrop=require('simURLDrop')

function simURLDrop.__addTypeCheck()
    local function wrapFunc(funcName,wrapperGenerator)
        _G['simURLDrop'][funcName]=wrapperGenerator(_G['simURLDrop'][funcName])
    end

end

sim.registerScriptFuncHook('sysCall_init','simURLDrop.__addTypeCheck',true)

return simURLDrop
