-- simWS lua type-checking wrapper
-- (this file is automatically generated: do not edit)
require 'checkargs'

local simWS=require('simWS')

function simWS.__addTypeCheck()
    local function wrapFunc(funcName,wrapperGenerator)
        _G['simWS'][funcName]=wrapperGenerator(_G['simWS'][funcName])
    end

end

sim.registerScriptFuncHook('sysCall_init','simWS.__addTypeCheck',true)

return simWS
